name: Build

on: workflow_dispatch
jobs:
 build-windows:
    runs-on: windows-latest
    name: Build on windows-amd64
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: ilammy/setup-nasm@v1.2.1
      - name: Update binaries
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          $Env:CC='clang'
          $Env:CXX='clang++'
          
          git clone -b workflows-test --recursive https://github.com/cirospaciari/socketify.py.git
          cd socketify.py\src\socketify\native
          vcpkg install libuv:x64-windows
          vcpkg install zlib:x64-windows-static-md
          vcpkg integrate install
          cp C:\vcpkg\installed\x64-windows\bin\uv.dll ..\uv.dll
         
          cd ..\uWebSockets\uSockets\boringssl 
          mkdir amd64 
          cd amd64
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja .. && ninja crypto ssl
          
          cd ..\..\..\..\native

          cd ..\uWebSockets\uSockets
          clang -D_DLL -Wpedantic -Wall -Wextra -Wsign-conversion -Wconversion -D WIN32_LEAN_AND_MEAN  -I C:\vcpkg\packages\libuv_x64-windows\include -I src -I boringssl\include -DUWS_WITH_PROXY -DLIBUS_USE_OPENSSL -DLIBUS_USE_LIBUV -pthread -std=c11 -O3 -c src\*.c src\eventing\*.c src\crypto\*.c
          clang++ -D_DLL -Wpedantic -Wall -Wextra -Wsign-conversion -Wconversion -D WIN32_LEAN_AND_MEAN  -I C:\vcpkg\packages\libuv_x64-windows\include -I boringssl\include -DUWS_WITH_PROXY -DLIBUS_USE_OPENSSL -DLIBUS_USE_LIBUV -pthread -std=c++2a -O3 -c src\crypto\*.cpp
          cd ..\..\native
          clang++ -D_DLL -Wpedantic -Wall -Wextra -Wsign-conversion -Wconversion -D WIN32_LEAN_AND_MEAN -I C:\vcpkg\packages\libuv_x64-windows\include -I .\src -I ..\uWebSockets\src -I ..\uWebSockets\uSockets\src -I ..\uWebSockets\capi -I C:\vcpkg\packages\zlib_x64-windows-static-md\include -I ..\uWebSockets\uSockets\boringssl\include -pthread -std=c++2a -c -O3 .\src\libsocketify.cpp 
          clang++ -D_DLL -Wpedantic -Wall -Wextra -Wsign-conversion -Wconversion -shared -o ..\libsocketify_windows_amd64.dll  libsocketify.o ..\uWebSockets\uSockets\*.o ..\uWebSockets\uSockets\boringssl\amd64\ssl\ssl.lib ..\uWebSockets\uSockets\boringssl\amd64\crypto\crypto.lib C:\vcpkg\packages\zlib_x64-windows-static-md\lib\zlib.lib -luv -L C:\vcpkg\packages\libuv_x64-windows\lib -nodefaultlibs -lmsvcrt -lvcruntime -lucrt -ladvapi32
          
          cd ..\
          git add libsocketify_windows_amd64.dll
          git add uv.dll
          git config --global user.email "ciro.spaciari@gmail.com"
          git config --global user.name "Ciro Spaciari"
          git commit -a -m "[GitHub Actions] Updated windows-amd64 binaries" || true
          git push "https://cirospaciari:${{ secrets.BUILDTOKEN }}@github.com/cirospaciari/socketify.py.git" workflows-test
