name: Build

on: workflow_dispatch
jobs:
 build-windows:
    runs-on: windows-latest
    name: Build on windows-amd64
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: ilammy/setup-nasm@v1.2.1
      - name: Update binaries
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          $Env:CC='clang'
          $Env:CXX='clang++'
          
          git clone -b workflows-test --recursive https://github.com/cirospaciari/socketify.py.git
          cd socketify.py\src\socketify\native
          vcpkg install libuv:x64-windows
          vcpkg integrate install
          
          copy C:\vcpkg\installed\x64-windows\bin\uv.dll ..\uv.dll
         
          cd ..\uWebSockets\uSockets\boringssl 
          mkdir amd64 
          cd amd64
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja .. && ninja crypto ssl
          
          cd ..\..\..\..\
          cl /MD /W3 /D WIN32_LEAN_AND_MEAN /D "UWS_NO_ZLIB" /D "UWS_WITH_PROXY" /D "LIBUS_USE_LIBUV" /I native/src/ /I uWebSockets/capi /I uWebSockets/uSockets/boringssl/include /D "LIBUS_USE_OPENSSL" /std:c++20 /I C:\vcpkg\packages\libuv_x64-windows\include /I uWebSockets/uSockets/src uWebSockets/uSockets/src/*.c uWebSockets/uSockets/src/crypto/sni_tree.cpp uWebSockets/uSockets/src/eventing/*.c uWebSockets/uSockets/src/crypto/*.c /I uWebSockets/src /EHsc /O3 /LD ./native/src/libsocketify.cpp advapi32.lib uWebSockets/uSockets/boringssl/amd64/ssl/ssl.lib uWebSockets/uSockets/boringssl/amd64/crypto/crypto.lib /link C:\vcpkg\installed\x64-windows\lib\uv.lib /OUT:libsocketify_windows_amd64.dll 

          cd ..\
          git add libsocketify_windows_amd64.dll
          git add uv.dll
          git config --global user.email "ciro.spaciari@gmail.com"
          git config --global user.name "Ciro Spaciari"
          git commit -a -m "[GitHub Actions] Updated windows-amd64 binaries" || true
          git push "https://cirospaciari:${{ secrets.BUILDTOKEN }}@github.com/cirospaciari/socketify.py.git" workflows-test
