name: Apple Silicon + libuv Build
on: workflow_dispatch
jobs:
 build-macos:
    runs-on: macos-11.0
    name: Build on darwin-arm64
    steps:
      - name: Update binaries
        run: |
          brew install autoconf automake libtool cmake
          git clone --branch v1.44.2 --recursive https://github.com/libuv/libuv.git
          cd libuv
          cmake . -DCMAKE_SYSTEM_NAME=Darwin -DCMAKE_C_COMPILER=arm64-apple-macos11-gcc
          cmake --build . -DCMAKE_SYSTEM_NAME=Darwin -DCMAKE_C_COMPILER=arm64-apple-macos11-gcc
          ls *