name: Windows Build

on: workflow_dispatch
jobs:
 build-windows:
    runs-on: windows-latest
    name: Build on windows-amd64
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: ilammy/setup-nasm@v1.2.1
      - name: Update binaries
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          $Env:CC='clang'
          $Env:CXX='clang++'
          
          vcpkg install libuv:x64-windows-static-md
          dir C:\vcpkg\installed\x64-windows-static-md\lib
          dir C:\vcpkg\installed\x64-windows-static-md\lib\libuv
